#!/usr/bin/env python
opcodes = [
        'ADC',
        'AND',
        'ASL',
        'BCC',
        'BCS',
        'BEQ',
        'BIT',
        'BMI',
        'BNE',
        'BPL',
        'BRK',
        'BVC',
        'BVS',
        'CLC',
        'CLD',
        'CLI',
        'CLV',
        'CMP',
        'CPX',
        'CPY',
        'DEC',
        'DEX',
        'DEY',
        'EOR',
        'INC',
        'INX',
        'INY',
        'JMP',
        'JSR',
        'LDA',
        'LDX',
        'LDY',
        'LSR',
        'NOP',
        'ORA',
        'PHA',
        'PHP',
        'PLA',
        'PLP',
        'ROL',
        'ROR',
        'RTI',
        'RTS',
        'SBC',
        'SEC',
        'SED',
        'SEI',
        'STA',
        'STX',
        'STY',
        'TAX',
        'TAY',
        'TSX',
        'TXA',
        'TXS',
        'TYA'
]

for i, mnem in enumerate(opcodes):
    map0 = (ord(mnem[0]) & 0x1F)
    map1 = (ord(mnem[1]) & 0x1F)
    map2 = (ord(mnem[2]) & 0x1F)
    val = (map0 << 10) + (map1 << 5) + map2
    print(f"                .word {"${:04x}".format(val)}    ; {mnem}   - {"${:02x}".format(i)}   ({"${:02x}".format(2* i)})")
