//
// Created by Peter Köllner on 22/1/26.
//

#include "../include/haiku6502/cpu.h"

namespace haiku6502 {
    Instruction operations[256] {
        // 0x00
        Instruction(BRK, IMPLIED, 2, 7),
        Instruction(ORA, INDEXED_INDIRECT_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(ORA, ZERO, 2, 3),
        Instruction(ASL, ZERO, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(PHP, IMPLIED, 1, 2),
        Instruction(ORA, IMMEDIATE, 2, 2),
        Instruction(ASL, ACCU, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(ORA, ABSOLUTE, 3, 4),
        Instruction(ASL, ABSOLUTE, 3, 6),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0x10
        Instruction(BPL, RELATIVE, 2, 2),
        Instruction(ORA, INDIRECT_INDEXED_Y, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(ORA, ZERO_X, 2, 4),
        Instruction(ASL, ZERO_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(CLC, IMPLIED, 1, 2),
        Instruction(ORA, ABSOLUTE_Y, 3, 4),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(ORA, ABSOLUTE_X, 3, 4),
        Instruction(ASL, ABSOLUTE_X, 3,7),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0x20
        Instruction(JSR, ABSOLUTE, 3, 6),
        Instruction(AND, INDEXED_INDIRECT_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(BIT, ZERO, 2, 3),
        Instruction(AND, ZERO, 2, 3),
        Instruction(ROL, ZERO, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(PLP, IMPLIED, 1, 2),
        Instruction(AND, IMMEDIATE, 2, 2),
        Instruction(ROL, ACCU, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(BIT, ABSOLUTE, 3, 4),
        Instruction(AND, ABSOLUTE, 3,4),
        Instruction(ROL, ABSOLUTE, 3, 6),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0x30
        Instruction(BMI, RELATIVE, 2, 2),
        Instruction(AND, INDIRECT_INDEXED_Y, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(AND, ZERO_X, 2, 4),
        Instruction(ROL, ZERO_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(SEC, IMPLIED, 1, 2),
        Instruction(AND, ABSOLUTE_Y, 3, 4),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(AND, ABSOLUTE_X, 3, 4),
        Instruction(ROL, ABSOLUTE_X, 3, 7),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0x40
        Instruction(RTI, IMPLIED, 1, 6),
        Instruction(EOR, INDEXED_INDIRECT_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(EOR, ZERO, 2, 3),
        Instruction(LSR, ZERO, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(PHA, IMPLIED, 1, 2),
        Instruction(EOR, IMMEDIATE, 2, 2),
        Instruction(LSR, ACCU, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(JMP, ABSOLUTE, 3, 3),
        Instruction(EOR, ABSOLUTE, 3, 4),
        Instruction(LSR, ABSOLUTE, 3, 6),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0x50
        Instruction(BVC, RELATIVE, 2, 2),
        Instruction(EOR, INDIRECT_INDEXED_Y, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(EOR, ZERO_X, 2, 4),
        Instruction(LSR, ZERO_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(CLI, IMPLIED, 1, 2),
        Instruction(EOR, ABSOLUTE_Y, 3, 4),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(EOR, ABSOLUTE_X, 3, 4),
        Instruction(LSR, ABSOLUTE_X, 3, 7),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0x60
        Instruction(RTS, IMPLIED, 1, 6),
        Instruction(ADC, INDEXED_INDIRECT_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(ADC, ZERO, 2, 3),
        Instruction(ROR, ZERO, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(PLA, IMPLIED, 1, 4),
        Instruction(ADC, IMMEDIATE, 2, 2),
        Instruction(ROR, ACCU, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(JMP, ABSOLUTE_INDIRECT, 3, 5),
        Instruction(ADC, ABSOLUTE, 3, 4),
        Instruction(ROR, ABSOLUTE, 3, 6),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0x70
        Instruction(BVS, RELATIVE, 2, 2),
        Instruction(ADC, INDIRECT_INDEXED_Y, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(ADC, ZERO_X, 2, 4),
        Instruction(ROR, ZERO_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(SEI, IMPLIED, 1, 2),
        Instruction(ADC, ABSOLUTE_Y,3, 4),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(ADC, ABSOLUTE_X, 3, 4),
        Instruction(ROR, ABSOLUTE_X, 3, 7),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0x80
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(STA, INDEXED_INDIRECT_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(STY, ZERO, 2, 3),
        Instruction(STA, ZERO, 2, 3),
        Instruction(STX, ZERO, 2, 3),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(DEY, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(TXA, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(STY, ABSOLUTE, 3, 4),
        Instruction(STA, ABSOLUTE, 3, 4),
        Instruction(STX, ABSOLUTE, 3, 4),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0x90
        Instruction(BCC, RELATIVE, 2, 2),
        Instruction(STA, INDIRECT_INDEXED_Y, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(STY, ZERO_X, 2, 4),
        Instruction(STA, ZERO_X, 2, 4),
        Instruction(STX, ZERO_Y, 2, 4),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(TYA, IMPLIED, 1, 2),
        Instruction(STA, ABSOLUTE_Y, 3, 5),
        Instruction(TXS, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(STY, ABSOLUTE_X, 3, 5),
        Instruction(STA, ABSOLUTE_X, 3, 5),
        Instruction(STX, ABSOLUTE_Y, 3, 5),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0xA0
        Instruction(LDY, IMMEDIATE, 2, 2),
        Instruction(LDA, INDEXED_INDIRECT_X, 2, 6),
        Instruction(LDX, IMMEDIATE, 2, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(LDY, ZERO, 2, 3),
        Instruction(LDA, ZERO, 2, 3),
        Instruction(LDX, ZERO, 2, 3),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(TAY, IMPLIED, 1, 2),
        Instruction(LDA, IMMEDIATE, 2, 2),
        Instruction(TAX, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(LDY, ABSOLUTE, 3, 4),
        Instruction(LDA, ABSOLUTE, 3, 4),
        Instruction(LDX, ABSOLUTE, 3, 4),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0xB0
        Instruction(BCS, RELATIVE, 2, 2),
        Instruction(LDA, INDIRECT_INDEXED_Y, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(LDY, ZERO_X, 2, 4),
        Instruction(LDA, ZERO_X, 2, 4),
        Instruction(LDX, ZERO_Y, 2, 4),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(CLV, IMPLIED, 1, 2),
        Instruction(LDA, ABSOLUTE_Y, 3, 4),
        Instruction(TSX, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(LDY, ABSOLUTE_X, 3, 4),
        Instruction(LDA, ABSOLUTE_X, 3, 4),
        Instruction(LDX, ABSOLUTE_Y, 3, 4),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0xC0
        Instruction(CPY, IMMEDIATE, 2, 2),
        Instruction(CMP, INDEXED_INDIRECT_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(CPY, ZERO, 2, 3),
        Instruction(CMP, ZERO, 2, 3),
        Instruction(DEC, ZERO, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(INY, IMPLIED, 1, 2),
        Instruction(CMP, IMMEDIATE, 2, 2),
        Instruction(DEX, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(CPY, ABSOLUTE, 3, 4),
        Instruction(CMP, ABSOLUTE, 3, 4),
        Instruction(DEC, ABSOLUTE, 3, 6),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0xD0
        Instruction(BNE, RELATIVE, 2, 2),
        Instruction(CMP, INDIRECT_INDEXED_Y, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(CMP, ZERO_X, 2, 4),
        Instruction(DEC, ZERO_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(CLD, IMPLIED, 1, 2),
        Instruction(CMP, ABSOLUTE_Y, 3, 4),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(CMP, ABSOLUTE_X, 3, 4),
        Instruction(DEC, ABSOLUTE_X, 3, 7),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0xE0
        Instruction(CPX, IMMEDIATE, 2, 2),
        Instruction(SBC, INDEXED_INDIRECT_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(CPX, ZERO, 2, 3),
        Instruction(SBC, ZERO, 2, 3),
        Instruction(INC, ZERO, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(INX, IMPLIED, 1, 2),
        Instruction(SBC, IMMEDIATE, 2, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(CPX, ABSOLUTE, 3, 4),
        Instruction(SBC, ABSOLUTE, 3, 4),
        Instruction(INC, ABSOLUTE, 3, 6),
        Instruction(NOP, IMPLIED, 1, 2),

        // 0xF0
        Instruction(BEQ, RELATIVE, 2, 2),
        Instruction(SBC, INDIRECT_INDEXED_Y, 2, 5),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(SBC, ZERO_X, 2, 4),
        Instruction(INC, ZERO_X, 2, 6),
        Instruction(NOP, IMPLIED, 1, 2),

        Instruction(SED, IMPLIED, 1, 2),
        Instruction(SBC, ABSOLUTE_Y, 3, 4),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(NOP, IMPLIED, 1, 2),
        Instruction(SBC, ABSOLUTE_X, 3, 4),
        Instruction(INC, ABSOLUTE_X, 3, 4),
        Instruction(NOP, IMPLIED, 1, 2)

    };
}